name: Python CI

on:
  push:
    branches:
    - main
    - feature/*
    - hotfix/*
  pull_request:
    branches: 
    - main
    - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Lint with black
      run: |
        python -m black --check .
    - name: Test with unittest
      run: |
        python -m pytest 
        
