name: Python CI

on:
  push:
    branches:
    - main
    - feature/*
    - hotfix/*
  pull_request:
    branches: 
    - main
    - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install -r requirements.txt
        
    - name: Lint
      run: |
        python -m black --check .
        
    - name: Test
      run: |
        python -m unittest 
